// -----------------------------------------------------------------------------
//  GENERATED FILE - DO NOT EDIT BY HAND
//  Regenerate with:  python tools/generate_catalog.py
//  Sources:          Contenido (order) + Catalogo_Paquetes.md (categories)
//
//  144 unique packages. The batch script lists 278 entries for these same
//  144 packages; the duplicates are dropped here, first occurrence wins.
//
//  Note: Catalogo_Paquetes.md claims 145 unique packages; the actual union of
//  the batch list and the markdown list is 144 (the "Otros" section header
//  says 4 but lists 3). This header follows the real data.
// -----------------------------------------------------------------------------
#pragma once

// Nota: este header NO incluye "daso/catalog.hpp". Lo incluye el propio
// catalog.hpp al final, despues de haber definido PackageEntry / RiskTier /
// Category, para que las capas superiores vean el catalogo sin incluir datos.

#include <array>
#include <cstddef>

namespace daso::detail {

using CatalogRecord = PackageEntry;

inline constexpr std::array<CatalogRecord, 144> kCatalogRecords{{
    { "com.android.theme.font.sanfrancisco",
      "San Francisco", "San Francisco",
      "La tipografía de sistema de iOS.",
      "The iOS system font.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.storopia",
      "Tipografía: Storopia", "Font: Storopia",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.sansserif",
      "Tipografía: Sansserif", "Font: Sansserif",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.leaf",
      "Icono temático: Leaf", "Themed icon: Leaf",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.meow",
      "Icono temático: Meow", "Themed icon: Meow",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.pebble",
      "Icono temático: Pebble", "Themed icon: Pebble",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "org.lineageos.overlay.customization.blacktheme",
      "Overlay de personalización: Blacktheme", "Customisation overlay: Blacktheme",
      "Ajuste de personalización de la ROM.",
      "A ROM customisation tweak.",
      RiskTier::Caution, Category::Themes },
    { "com.android.systemui.clocks.metro",
      "Reloj de SystemUI: Metro", "SystemUI clock: Metro",
      "Un diseño de reloj para la barra de estado.",
      "One status-bar clock design.",
      RiskTier::Caution, Category::SystemUi },
    { "org.risingos.backgrounds",
      "Componente de la ROM: Backgrounds", "ROM component: Backgrounds",
      "Componente que no aporta nada en el uso diario del móvil.",
      "Component that adds nothing to everyday phone use.",
      RiskTier::Caution, Category::CustomRom },
    { "com.libremobileos.sidebar",
      "Barra lateral", "Sidebar",
      "Barra lateral del launcher.",
      "The launcher's sidebar.",
      RiskTier::Caution, Category::Other },
    { "org.omnirom.omnijaws",
      "Componente de la ROM: Omnijaws", "ROM component: Omnijaws",
      "Componente que no aporta nada en el uso diario del móvil.",
      "Component that adds nothing to everyday phone use.",
      RiskTier::Caution, Category::CustomRom },
    { "com.android.internal.display.cutout.emulation.corner",
      "Emulación de recorte: Corner", "Cutout emulation: Corner",
      "Simula un recorte de pantalla distinto al real.",
      "Fakes a display cutout different from the real one.",
      RiskTier::Caution, Category::Aosp },
    { "com.android.internal.display.cutout.emulation.double",
      "Emulación de recorte: Double", "Cutout emulation: Double",
      "Simula un recorte de pantalla distinto al real.",
      "Fakes a display cutout different from the real one.",
      RiskTier::Caution, Category::Aosp },
    { "com.android.uwb.resources",
      "Recursos UWB", "UWB resources",
      "Textos e iconos de Ultra Wideband.",
      "Ultra Wideband strings and icons.",
      RiskTier::Caution, Category::Aosp },
    { "com.android.cts.priv.ctsshim",
      "Shim de pruebas CTS", "CTS test shim",
      "Andamiaje de pruebas de compatibilidad. Solo lo usan las compilaciones de QA.",
      "Compatibility test shim. Only QA builds use it.",
      RiskTier::Safe, Category::Aosp },
    { "com.android.theme.icon_pack.gradicon.android",
      "Pack de iconos: Android", "Icon pack: Android",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.scroll",
      "Icono temático: Scroll", "Themed icon: Scroll",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.square",
      "Icono temático: Square", "Themed icon: Square",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.vessel",
      "Icono temático: Vessel", "Themed icon: Vessel",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.nostalgic.systemui",
      "Pack de iconos: Systemui", "Icon pack: Systemui",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.acherus.systemui",
      "Pack de iconos: Systemui", "Icon pack: Systemui",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.rounded.systemui",
      "Pack de iconos: Systemui", "Icon pack: Systemui",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.taperedrect",
      "Icono temático: Taperedrect", "Themed icon: Taperedrect",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.oos.android",
      "Pack de iconos: Android", "Icon pack: Android",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.nokiapure",
      "Tipografía: Nokiapure", "Font: Nokiapure",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.comfortaa",
      "Tipografía: Comfortaa", "Font: Comfortaa",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.comicsans",
      "Tipografía: Comicsans", "Font: Comicsans",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.amarante",
      "Tipografía: Amarante", "Font: Amarante",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.aclonica",
      "Tipografía: Aclonica", "Font: Aclonica",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.nothingdotheadline",
      "Tipografía: Nothingdotheadline", "Font: Nothingdotheadline",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.outline.systemui",
      "Pack de iconos: Systemui", "Icon pack: Systemui",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.rounded.android",
      "Pack de iconos: Android", "Icon pack: Android",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.xperia.systemui",
      "Pack de iconos: Systemui", "Icon pack: Systemui",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.victor.systemui",
      "Pack de iconos: Systemui", "Icon pack: Systemui",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.pui.systemui",
      "Pack de iconos: Systemui", "Icon pack: Systemui",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "org.omnirom.omnijaws.auto_generated_rro_product__",
      "Overlay de ROM: Omnijaws", "ROM overlay: Omnijaws",
      "Recurso generado automáticamente por la ROM para un producto concreto.",
      "Resource auto-generated by the ROM for one specific product.",
      RiskTier::Caution, Category::CustomRom },
    { "org.lineageos.sm6375.EuiccOverlay",
      "Overlay de eSIM (SM6375)", "eSIM overlay (SM6375)",
      "Overlay de eSIM específico del chip SM6375.",
      "eSIM overlay specific to the SM6375 chipset.",
      RiskTier::Safe, Category::Overlay },
    { "org.lineageos.lineageparts.auto_generated_rro_product__",
      "Overlay de ROM: Lineageparts", "ROM overlay: Lineageparts",
      "Recurso generado automáticamente por la ROM para un producto concreto.",
      "Resource auto-generated by the ROM for one specific product.",
      RiskTier::Caution, Category::CustomRom },
    { "org.lineageos.lineagesettings.auto_generated_rro_product__",
      "Overlay de ROM: Lineagesettings", "ROM overlay: Lineagesettings",
      "Recurso generado automáticamente por la ROM para un producto concreto.",
      "Resource auto-generated by the ROM for one specific product.",
      RiskTier::Caution, Category::CustomRom },
    { "com.android.settings.overlay.miami",
      "Overlay de Ajustes", "Settings overlay",
      "Recurso de overlay aplicado a Ajustes.",
      "Overlay resource applied to Settings.",
      RiskTier::Caution, Category::Overlay },
    { "com.android.systemui.auto_generated_rro_product__",
      "Overlay de ROM: Systemui", "ROM overlay: Systemui",
      "Recurso generado automáticamente por la ROM para un producto concreto.",
      "Resource auto-generated by the ROM for one specific product.",
      RiskTier::Caution, Category::SystemUi },
    { "com.android.systemui.clocks.bignum",
      "Reloj de SystemUI: Bignum", "SystemUI clock: Bignum",
      "Un diseño de reloj para la barra de estado.",
      "One status-bar clock design.",
      RiskTier::Caution, Category::SystemUi },
    { "com.android.systemui.plugin.globalactions.wallet",
      "Acción rápida de Wallet", "Wallet quick action",
      "Acceso al monedero desde el menú de apagado.",
      "Wallet access from the power menu.",
      RiskTier::Caution, Category::SystemUi },
    { "com.android.avatarpicker",
      "Selector de avatar", "Avatar picker",
      "Elige la foto de perfil de la cuenta. Nadie lo usa en la práctica.",
      "Picks the account profile photo. Nobody uses it in practice.",
      RiskTier::Safe, Category::Aosp },
    { "android.overlay.moto.common",
      "Overlay base: Common", "Base overlay: Common",
      "Overlay del sistema que ajusta recursos comunes.",
      "System overlay that adjusts common resources.",
      RiskTier::Caution, Category::Overlay },
    { "io.chaldeaprjkt.gamespace.auto_generated_rro_product__",
      "Overlay de GameSpace", "GameSpace overlay",
      "Espacio de juego de la ROM.",
      "The ROM's game space.",
      RiskTier::Caution, Category::Other },
    { "com.mtg.gmssettingsoverlay",
      "Overlay de Ajustes GMS", "GMS settings overlay",
      "Ajustes de servicios de Google de la ROM.",
      "The ROM's Google services settings.",
      RiskTier::Safe, Category::Overlay },
    { "vendor.qti.hardware.cacert.server",
      "Servidor CA de Qualcomm", "Qualcomm CA server",
      "Servidor de certificados raíz del fabricante.",
      "Vendor root certificate server.",
      RiskTier::Caution, Category::Vendor },
    { "com.android.htmlviewer",
      "Visor HTML", "HTML viewer",
      "Visor de HTML antiguo, ya innecesario en los navegadores actuales.",
      "Legacy HTML viewer, already unnecessary in current browsers.",
      RiskTier::Safe, Category::Aosp },
    { "com.android.companiondevicemanager",
      "Gestor de dispositivos vinculados", "Companion device manager",
      "Empareja el reloj y los auriculares con el móvil.",
      "Pairs a watch and headphones with the phone.",
      RiskTier::Caution, Category::Aosp },
    { "com.android.virtualmachine.res",
      "Recursos de máquina virtual", "Virtual machine resources",
      "Recursos para ejecutar aplicaciones virtualizadas.",
      "Resources for running virtualised apps.",
      RiskTier::Caution, Category::Aosp },
    { "com.android.scheduling",
      "Planificador de tareas", "Job scheduler",
      "Planificador de tareas en segundo plano del sistema.",
      "The system background job scheduler.",
      RiskTier::Caution, Category::Aosp },
    { "com.stevesoltys.seedvault",
      "SeedVault", "SeedVault",
      "Copia de seguridad del sistema. Android la usa por debajo.",
      "System backup. Android relies on it underneath.",
      RiskTier::Caution, Category::Other },
    { "com.android.adservices",
      "Servicios de publicidad", "Advertising services",
      "Plataforma de anuncios y filtrado de publicidad por red.",
      "Ad platform and network-based ad filtering.",
      RiskTier::Caution, Category::Aosp },
    { "com.android.appsearch",
      "Buscador de aplicaciones", "App search",
      "Buscador global de aplicaciones.",
      "Global application search.",
      RiskTier::Caution, Category::Aosp },
    { "com.android.health.connect.backuprestore",
      "Copia de Salud Conectada", "Health Connect backup",
      "Copia de seguridad de los datos de salud.",
      "Backup of Health Connect data.",
      RiskTier::Caution, Category::Aosp },
    { "com.android.federatedcompute.services",
      "Computación federada", "Federated compute",
      "Aprendizaje federado en segundo plano.",
      "Background federated learning.",
      RiskTier::Caution, Category::Aosp },
    { "com.google.android.googlequicksearchbox",
      "Buscador de Google", "Google search box",
      "Caja de búsqueda de Google en el launcher.",
      "Google search box in the launcher.",
      RiskTier::Caution, Category::Google },
    { "com.android.theme.icon_pack.plumpy.systemui",
      "Pack de iconos: Systemui", "Icon pack: Systemui",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.jetbrainsmono",
      "JetBrains Mono", "JetBrains Mono",
      "Tipografía monoespaciada para programadores.",
      "Monospaced font aimed at programmers.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.samsungone",
      "Tipografía: Samsungone", "Font: Samsungone",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.nunito",
      "Tipografía: Nunito", "Font: Nunito",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.cookierun",
      "Tipografía: Cookierun", "Font: Cookierun",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.gradicon.systemui",
      "Pack de iconos: Systemui", "Icon pack: Systemui",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.oswald",
      "Tipografía: Oswald", "Font: Oswald",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.coolstory",
      "Tipografía: Coolstory", "Font: Coolstory",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.sam.android",
      "Pack de iconos: Android", "Icon pack: Android",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.notoserifsource",
      "Tipografía: Notoserifsource", "Font: Notoserifsource",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.filled.android",
      "Pack de iconos: Android", "Icon pack: Android",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.quando",
      "Tipografía: Quando", "Font: Quando",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.circular.systemui",
      "Pack de iconos: Systemui", "Icon pack: Systemui",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.surfer",
      "Tipografía: Surfer", "Font: Surfer",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.pui.android",
      "Pack de iconos: Android", "Icon pack: Android",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.kai.android",
      "Pack de iconos: Android", "Icon pack: Android",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.ubuntu",
      "Tipografía: Ubuntu", "Font: Ubuntu",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.robotocondensed",
      "Tipografía: Robotocondensed", "Font: Robotocondensed",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.atkinson",
      "Tipografía: Atkinson", "Font: Atkinson",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.hexagon",
      "Icono temático: Hexagon", "Themed icon: Hexagon",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.ios",
      "Icono temático: Ios", "Themed icon: Ios",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.plumpy.android",
      "Pack de iconos: Android", "Icon pack: Android",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.squircle",
      "Icono temático: Squircle", "Themed icon: Squircle",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.victor.android",
      "Pack de iconos: Android", "Icon pack: Android",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.aurora.systemui",
      "Pack de iconos: Systemui", "Icon pack: Systemui",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.cylinder",
      "Icono temático: Cylinder", "Themed icon: Cylinder",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.oneplussans",
      "Tipografía: Oneplussans", "Font: Oneplussans",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.accuratist",
      "Tipografía: Accuratist", "Font: Accuratist",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.samsung",
      "Icono temático: Samsung", "Themed icon: Samsung",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.cloudy",
      "Icono temático: Cloudy", "Themed icon: Cloudy",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.roundedrect",
      "Icono temático: Roundedrect", "Themed icon: Roundedrect",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.aurora.android",
      "Pack de iconos: Android", "Icon pack: Android",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.linotte",
      "Tipografía: Linotte", "Font: Linotte",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.grandhotel",
      "Tipografía: Grandhotel", "Font: Grandhotel",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.flower",
      "Icono temático: Flower", "Themed icon: Flower",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.lato",
      "Tipografía: Lato", "Font: Lato",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.play",
      "Tipografía: Play", "Font: Play",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.circular.android",
      "Pack de iconos: Android", "Icon pack: Android",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.redressed",
      "Tipografía: Redressed", "Font: Redressed",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.dreams.basic",
      "Protectores básicos", "Basic dreams",
      "Protectores de pantalla integrados.",
      "Built-in screensavers.",
      RiskTier::Caution, Category::Aosp },
    { "com.android.photopicker",
      "Selector de fotos", "Photo picker",
      "El selector de fotos del sistema. Android 13 ya lo trae integrado.",
      "The system photo picker. Android 13 already ships it built in.",
      RiskTier::Safe, Category::Aosp },
    { "com.android.customization.themes",
      "Catálogo de temas", "Theme catalogue",
      "El catálogo de temas del sistema.",
      "The system theme catalogue.",
      RiskTier::Caution, Category::Themes },
    { "com.android.dreams.phototable",
      "Protector de fotos", "Photo table dream",
      "Protector de pantalla con fotos.",
      "Photo screensaver.",
      RiskTier::Caution, Category::Aosp },
    { "com.android.wallpaper.livepicker",
      "Selector de fondos", "Live wallpaper picker",
      "Selector de fondos de pantalla animados.",
      "Live wallpaper picker.",
      RiskTier::Caution, Category::Aosp },
    { "com.android.wallpaper",
      "Fondos de pantalla", "Wallpapers",
      "Servicio de fondos de pantalla del sistema.",
      "The system wallpaper service.",
      RiskTier::Caution, Category::Aosp },
    { "com.android.wallpaperbackup",
      "Copia de fondos", "Wallpaper backup",
      "Copia de seguridad del fondo de pantalla actual.",
      "Backup of the current wallpaper.",
      RiskTier::Caution, Category::Aosp },
    { "com.android.theme.font.harmonysans",
      "Tipografía: Harmonysans", "Font: Harmonysans",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.oos.systemui",
      "Pack de iconos: Systemui", "Icon pack: Systemui",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.systemui.clocks.growth",
      "Reloj de SystemUI: Growth", "SystemUI clock: Growth",
      "Un diseño de reloj para la barra de estado.",
      "One status-bar clock design.",
      RiskTier::Caution, Category::SystemUi },
    { "com.android.theme.icon_pack.lorn.android",
      "Pack de iconos: Android", "Icon pack: Android",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.internal.systemui.navbar.threebutton",
      "Barra de 3 botones", "Three-button navbar",
      "Variante de la barra de navegación con 3 botones.",
      "Navigation bar variant with three buttons.",
      RiskTier::Caution, Category::SystemUi },
    { "com.android.theme.font.sonysketch",
      "Tipografía: Sonysketch", "Font: Sonysketch",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.acherus.android",
      "Pack de iconos: Android", "Icon pack: Android",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.cocon",
      "Tipografía: Cocon", "Font: Cocon",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.rubik",
      "Tipografía: Rubik", "Font: Rubik",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.cagliostro",
      "Tipografía: Cagliostro", "Font: Cagliostro",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.systemui.clocks.numoverlap",
      "Reloj de SystemUI: Numoverlap", "SystemUI clock: Numoverlap",
      "Un diseño de reloj para la barra de estado.",
      "One status-bar clock design.",
      RiskTier::Caution, Category::SystemUi },
    { "com.android.theme.icon.roundedhexagon",
      "Icono temático: Roundedhexagon", "Themed icon: Roundedhexagon",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.xperia.android",
      "Pack de iconos: Android", "Icon pack: Android",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.oneplusslate",
      "Tipografía: Oneplusslate", "Font: Oneplusslate",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.systemui.clocks.calligraphy",
      "Reloj de SystemUI: Calligraphy", "SystemUI clock: Calligraphy",
      "Un diseño de reloj para la barra de estado.",
      "One status-bar clock design.",
      RiskTier::Caution, Category::SystemUi },
    { "com.android.theme.font.fifa2018",
      "Tipografía: Fifa2018", "Font: Fifa2018",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.heart",
      "Icono temático: Heart", "Themed icon: Heart",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.nothingdot",
      "Tipografía: Nothingdot", "Font: Nothingdot",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.kai.systemui",
      "Pack de iconos: Systemui", "Icon pack: Systemui",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.reemkufi",
      "Tipografía: Reemkufi", "Font: Reemkufi",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.stretched",
      "Icono temático: Stretched", "Themed icon: Stretched",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.outline.android",
      "Pack de iconos: Android", "Icon pack: Android",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.bariol",
      "Tipografía: Bariol", "Font: Bariol",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon_pack.sam.systemui",
      "Pack de iconos: Systemui", "Icon pack: Systemui",
      "Pack de iconos adicional. Solo desaparece de la galería de temas.",
      "Additional icon pack. It only disappears from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.icon.teardrop",
      "Icono temático: Teardrop", "Themed icon: Teardrop",
      "Un icono concreto de la galería de temas.",
      "A single icon from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.theme.font.exotwo",
      "Tipografía: Exotwo", "Font: Exotwo",
      "Una tipografía concreta de la galería de temas.",
      "A single font from the theme gallery.",
      RiskTier::Safe, Category::Themes },
    { "com.android.egg",
      "Huevo de Pascua", "Easter egg",
      "El huevo de Pascua de Android.",
      "The Android easter egg.",
      RiskTier::Caution, Category::Aosp },
    { "org.protonaosp.deviceconfig.auto_generated_rro_product__",
      "Overlay de ROM: Deviceconfig", "ROM overlay: Deviceconfig",
      "Recurso generado automáticamente por la ROM para un producto concreto.",
      "Resource auto-generated by the ROM for one specific product.",
      RiskTier::Caution, Category::CustomRom },
    { "org.protonaosp.deviceconfig",
      "Componente de la ROM: Deviceconfig", "ROM component: Deviceconfig",
      "Componente que no aporta nada en el uso diario del móvil.",
      "Component that adds nothing to everyday phone use.",
      RiskTier::Safe, Category::CustomRom },
    { "org.protonaosp.columbus.auto_generated_rro_product__",
      "Overlay de ROM: Columbus", "ROM overlay: Columbus",
      "Recurso generado automáticamente por la ROM para un producto concreto.",
      "Resource auto-generated by the ROM for one specific product.",
      RiskTier::Caution, Category::CustomRom },
    { "android.overlay.common",
      "Overlay base: Common", "Base overlay: Common",
      "Overlay del sistema que ajusta recursos comunes.",
      "System overlay that adjusts common resources.",
      RiskTier::Caution, Category::Overlay },
    { "android.overlay.target",
      "Overlay base: Target", "Base overlay: Target",
      "Overlay del sistema que ajusta recursos comunes.",
      "System overlay that adjusts common resources.",
      RiskTier::Caution, Category::Overlay },
    { "com.android.internal.display.cutout.emulation",
      "Emulación de recorte: Emulation", "Cutout emulation: Emulation",
      "Simula un recorte de pantalla distinto al real.",
      "Fakes a display cutout different from the real one.",
      RiskTier::Caution, Category::Aosp },
    { "com.google.android.marvin.talkback",
      "TalkBack", "TalkBack",
      "Lector de pantalla de accesibilidad.",
      "The TalkBack screen reader.",
      RiskTier::Caution, Category::Google },
    { "com.google.android.apps.wellbeing",
      "Bienestar Digital", "Digital Wellbeing",
      "Controles de tiempo de pantalla y modos de concentración.",
      "Screen time controls and focus modes.",
      RiskTier::Caution, Category::Google },
    { "com.org.protonaosp.deviceconfig.auto_generated_rro_product__",
      "Overlay de ROM: Deviceconfig", "ROM overlay: Deviceconfig",
      "Recurso generado automáticamente por la ROM para un producto concreto.",
      "Resource auto-generated by the ROM for one specific product.",
      RiskTier::Caution, Category::CustomRom },
    { "com.org.protonaosp.deviceconfig",
      "Componente de la ROM: Deviceconfig", "ROM component: Deviceconfig",
      "Componente que no aporta nada en el uso diario del móvil.",
      "Component that adds nothing to everyday phone use.",
      RiskTier::Safe, Category::CustomRom },
    { "com.org.protonaosp.columbus.auto_generated_rro_product__",
      "Overlay de ROM: Columbus", "ROM overlay: Columbus",
      "Recurso generado automáticamente por la ROM para un producto concreto.",
      "Resource auto-generated by the ROM for one specific product.",
      RiskTier::Caution, Category::CustomRom },
    { "com.android.overlay.common",
      "Componente del sistema: Common", "System component: Common",
      "Componente que no aporta nada en el uso diario del móvil.",
      "Component that adds nothing to everyday phone use.",
      RiskTier::Caution, Category::Overlay },
    { "com.android.overlay.target",
      "Componente del sistema: Target", "System component: Target",
      "Componente que no aporta nada en el uso diario del móvil.",
      "Component that adds nothing to everyday phone use.",
      RiskTier::Caution, Category::Overlay },
}};

// Reglas de nivel vital, con el mismo patron `*` que usa el generador.
// Se emiten aqui para que C++ y Python compartan una unica fuente.
struct VitalRule {
  std::string_view pattern;
  std::string_view reason;
};

inline constexpr std::array<VitalRule, 23> kVitalRules{{
    { "com.android.systemui", "Barra de estado y panel de notificaciones." },
    { "com.android.settings", "Ajustes del sistema. Sin esto no hay configuración." },
    { "com.android.shell", "Consola ADB. Sin esto D.A.S.O no puede ejecutarse." },
    { "com.android.providers.settings", "Proveedor de Ajustes; las apps se apagan al quitarlo." },
    { "com.android.packageinstaller", "Instalador de paquetes del sistema." },
    { "com.android.permissioncontroller", "Controlador de permisos." },
    { "com.android.phone", "Telephonía." },
    { "com.android.server.telecom", "Servicio telefónico." },
    { "com.android.bluetooth", "Pila de Bluetooth." },
    { "com.android.nfc", "NFC." },
    { "com.android.emergency", "Llamadas de emergencia." },
    { "com.android.externalstorage", "Almacenamiento externo (SD)." },
    { "com.android.providers.contacts", "Proveedor de contactos." },
    { "com.android.providers.calendar", "Proveedor de calendario." },
    { "com.android.inputmethod.*", "Teclado del sistema. Sin teclado no se puede escribir." },
    { "com.google.android.inputmethod.*", "Teclado de Gboard." },
    { "com.android.launcher*", "Launcher del sistema: sin icono no se abre ninguna app." },
    { "com.android.launcher3*", "Launcher del sistema: sin icono no se abre ninguna app." },
    { "org.lineageos.launcher*", "Launcher del sistema: sin icono no se abre ninguna app." },
    { "com.miui.home", "Launcher del sistema: sin icono no se abre ninguna app." },
    { "com.sec.android.app.launcher*", "Launcher del sistema: sin icono no se abre ninguna app." },
    { "com.google.android.gms", "Servicios de Google. Quitarlos rompe notificaciones y cuentas." },
    { "android", "El propio framework de Android." },
}};

}  // namespace daso::detail
